### ISSUE TITLE
Error running Getting Started Tutorial

### ISSUE THREAD

**Issue by yukiaguan** [circles-arrows/blueprint41#13]
When the program runs to transaction.commit (); throwing wrong：Due to an unexpected state of the neo4j transaction, it seems impossible to insert the Person at this time.

**Comment by circles-arrows** [comment]
Hi @GuanYuMikasa , we are unable to reproduce this issue. Maybe your database service is not running, and if you use Neo4j Aura, maybe you specify wrong database name. What database you are using?

**Comment by yukiaguan** [comment]
I have successfully solved the problem，thank you.
