### ISSUE TITLE
Custom Logging in v4 Neo4jPersistenceProvider not working

### ISSUE THREAD

**Issue by msarvankmr** [circles-arrows/blueprint41#15]
Hi,
I used PersistenceProvider(v4) advancedConfig parameter customLogger property to enable logging  but still the information about the transaction and database connection details are not getting logged. Is there a way to enable logging if we use blueprint41? if somethings goes wrong we need the logs to investigate the issue
`var config = new AdvancedConfig()
        {
            SimpleLogging = false,
            CustomLogging= s =>
                logger.Error(s)
        };
        PersistenceProvider.CurrentPersistenceProvider = new Neo4jPersistenceProvider(
            settings.GraphDatabase.ConnectionString,
            settings.GraphDatabase.UserName, settings.GraphDatabase.Password, advancedConfig: config);`

**Comment by circles-arrows** [comment]
In v1.0.23, which was just released, Logging can be configured more extensively.
You can now, using AdvancedConfig, configure the following logging options:
- SimpleLogging, CustomLogging & CustomCypherLogging
- The LogDirectory (defaults to "%ApplicationFolder%\TransactionLogs")
- ThresholdInSeconds (defaults to 0, queries taking longer than this time will be logged in SimpleLogging and/or CustomCypherLogging)
- CustomLogging -> Action<string>
- CustomCypherLogging -> CypherLoggingHandler(string cypher, Dictionary<string, object?>? parameters, long elapsedMilliseconds, string? memberName, string? sourceFilePath, int sourceLineNumber);

Please let us know if you still run into issues!
