### ISSUE TITLE
Neo4j V5 Update

### ISSUE THREAD

**Issue by msarvankmr** [circles-arrows/blueprint41#16]
Hi,
Do you have any plan to release the new package with supports Neo4J V5, the current plugin is breaking in V5.  
Thanks

**Comment by circles-arrows** [comment]
We didn't look into the plugin yet and I also think some Cypher changes would be incompatible. This is planned to work on starting early April.

**Comment by circles-arrows** [comment]
Just an quick update:
We upgraded the plugin and are currently testing it.
We also made the Blueprint41.Neo4jDriver.v5 project which has some small problems left to fix.
Currently we are busy writing the cypher translation support for Neo4j v5

**Comment by msarvankmr** [comment]
Hi @circles-arrows ,
When this upgrade will be available?

**Comment by circles-arrows** [comment]
today ;)
