### ISSUE TITLE
Error running Getting Started Tutorial

### ISSUE THREAD

**Issue by EdMcdaniel** [circles-arrows/blueprint41#2]
I am getting an error trying to work through your Getting Started tutorial. All is well until I try to execute the "Run Custom Tool" command. I have attached a doc with screen shots and error text in hopes this will help diagnose my issue.
Ed

[Blueprint41 Error Issue.docx](https://github.com/circles-arrows/blueprint41/files/2361376/Blueprint41.Error.Issue.docx)

**Comment by circles-arrows** [comment]
Hello Ed,


Thank you for trying out Blueprint41 and thank you for reporting the issue!

I think I was able to replicate your issue. I hope this will work for you:
- First compile/build the HelloWorld.Generated project (and make sure you have zero errors).
- Then try to run the custom tool in the HelloWorld.Generated project.

One more thing, I noticed that you're using version 1.0.12 of Blueprint41, which contains a bug thats fixed in version 1.0.13. Please upgrade your Blueprint41 in Visual Studio: Tools -> NuGet Package Manager -> Manage NuGet Packages for Solution -> Updates


Let me know if you need any further assistance.

Good Luck,
Ren

**Comment by EdMcdaniel** [comment]
Updated my version of Blueprint41
[cid:image006.jpg@01D448E5.0BC7A150]

Rebuilt entire solution with no errors.
[cid:image007.jpg@01D448E5.0BC7A150]

Right click on HelloWorld.Generated Generate.tt and clicked on Run Custom Tool.
[cid:image005.png@01D448E3.15E25EC0]

Clicked on OK.

The tool is still looking for a dll in the all the wrong places.



Got the following error message:

Error                     An exception was thrown while trying to compile the transformation code. The following Exception was thrown:
System.IO.FileNotFoundException: Could not find a part of the path 'C:\Projects\HelloWorld\DataStore\bin\Debug\netstandard2.0\Blueprint41.dll'.
File name: 'C:\Projects\HelloWorld\DataStore\bin\Debug\netstandard2.0\Blueprint41.dll' ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Projects\HelloWorld\DataStore\bin\Debug\netstandard2.0\Blueprint41.dll'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.<>c.<.ctor>b__15_0(String x)
  at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__67`1.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__67`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.ImmutableArrayExtensions.AsImmutableOrEmpty[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Compilation.ValidateReferences[T](IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.WithReferences(IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonWithReferences(IEnumerable`1 newReferences)
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.PrepareNewCompilation()
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.Compile()
   at Microsoft.VisualStudio.TextTemplating.TransformationRunner.Compile(String source, String inputFile, IEnumerable`1 references, Boolean debug, SupportedLanguage language, String compilerOptions)  HelloWorld.Generated                   1




Ed McDaniel

**Comment by circles-arrows** [comment]
Hello Ed,

You're right, I am not sure how it got broken and why it was working on my computer at work, but I get the same result on my computer at home... I'll double check & fix the plugin when I have some time (will post here when it's fixed), but for now I can give you a workaround:

Edit the HelloWorld.Model it's project file to include the CopyLocalLockFileAssemblies option. After you edited it, it should look as follows:
&lt;Project Sdk="Microsoft.NET.Sdk">

&nbsp;&nbsp;&lt;PropertyGroup>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;TargetFramework>netstandard2.0&lt;/TargetFramework>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;CopyLocalLockFileAssemblies>true&lt;/CopyLocalLockFileAssemblies>
&nbsp;&nbsp;&lt;/PropertyGroup>

&nbsp;&nbsp;&lt;ItemGroup>
&nbsp;&nbsp;&nbsp;&nbsp;&lt;PackageReference Include="Blueprint41" Version="1.*" />
&nbsp;&nbsp;&lt;/ItemGroup>

&lt;/Project>

Edit the Generated.tt file to look like this:
&lt;#@ template language="C#" hostSpecific="true" debug="true" #>
&lt;#@ assembly name="netstandard, Version=2.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51" #>
&lt;#@ assembly name="$(ProjectDir)..\HelloWorld.Model\bin\Debug\netstandard2.0\System.CodeDom.dll" #>
&lt;#@ assembly name="$(ProjectDir)..\HelloWorld.Model\bin\Debug\netstandard2.0\Blueprint41.dll" #>
&lt;#@ assembly name="$(ProjectDir)..\HelloWorld.Model\bin\Debug\netstandard2.0\HelloWorld.Model.dll" #>
&lt;#@ import namespace="System.IO" #>
&lt;#@ import namespace="Blueprint41.DatastoreTemplates" #>
&lt;#@ output extension=".txt" #>
&lt;#   
&nbsp;&nbsp;&nbsp;&nbsp;try
&nbsp;&nbsp;&nbsp;&nbsp;{
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Generator.Execute<HelloWorld.Model.Datastore>(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;new GeneratorSettings(
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Path.GetDirectoryName(Host.TemplateFile),
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;"Domain.Data"
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;)
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;);
#>
Success!
&lt;#
&nbsp;&nbsp;&nbsp;&nbsp;}
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;catch (Exception e)
&nbsp;&nbsp;&nbsp;&nbsp;{
#>
Error Message: &lt;#= e.Message #>
Stack Trace:
&lt;#= e.StackTrace #>
&lt;#
&nbsp;&nbsp;&nbsp;&nbsp;}
#>

**Comment by EdMcdaniel** [comment]
Thanks for the work around, it worked. I can move forward with the getting started tutorial.
Ed

**Comment by EdMcdaniel** [comment]
I found another issue.

I was able to use your workaround and execute Run Custom Tool without error. Went on to Blueprint CRUD. When I try to debug my HelloWorld application the code in HelloWorld Program.cs Main throws an error on the line;

model.Execute(true);

Error Message = There is no procedure with the name `blueprint41.functionalid.list` registered for this database instance. Please ensure you've spelled the procedure name correctly and that the procedure is properly deployed.

I searched the Blueprint41 assembly using Visual Studio Object Browser and did not see the functionalid.list property or method.

Am I looking in the right place?

Ed

**Comment by circles-arrows** [comment]
Hello Ed,

I think you didn't install the "Blueprint41 plugin" into Neo4j. Instructions on how to do that can be found here: [https://github.com/circles-arrows/blueprint41/wiki/Extension-and-Plugins#neo4j-plugins](https://github.com/circles-arrows/blueprint41/wiki/Extension-and-Plugins#neo4j-plugins)

The plugin adds functionality to Neo4j for generating unique id's, similar to auto-increment primary keys in relational databases.
The APOC plugin is used by Bluerint41 to implement the free-text search feature. I suspect you can get away with not installing that plugin into Neo4j till you need that functionality.

**Comment by EdMcdaniel** [comment]
With the help of your work-arounds and my installing addins properly I now have a working console app using Blueprint41, thank you.
Ed

As a suggestion it would be nice if your getting started tutorial had another section to demonstrate how to edit the code in the HelloWorld console app to use the model generated in the Blueprint41 Graph Modeler tutorial.

**Comment by circles-arrows** [comment]
That is great news Ed!

I updated the plugin to solve the issues/bugs you encountered and your suggestion is added to the list of improvements to the getting started documentation.

If you have any more suggestions for the documentation, blueprint41 or the modeller, please let me know. Feedback is vital to improving!
