### ISSUE TITLE
Enterprise Only features

### ISSUE THREAD

**Issue by duanemck** [circles-arrows/blueprint41#23]
I am using the free version of Neo4J and am trying to run through the Getting Started.

When I call `model.Execute(true)` I'm getting the following error:

```
DatabaseException: Unable to create Constraint( type='NODE PROPERTY EXISTENCE', schema=(:Person {Uid}) ):
Property existence constraint requires Neo4j Enterprise Edition
```

Is there a way to disabled the Enterprise features like Node Property Existence constraints?

**Comment by neo-blueprint41** [comment]
Thanks for reporting.
We will investigate this issue and will let you once it is fixed.

**Comment by neo-blueprint41** [comment]
We have fixed the issue and it will be part of the next release.
