### ISSUE TITLE
Implement MSBuild solution to generating Blueprint41 entity classes instead of via T4 templates

### ISSUE THREAD

**Issue by circles-arrows** [circles-arrows/blueprint41#28]
Since T4 is not available on all platforms, the code generation should run as part of the build process using [inline tasks](https://learn.microsoft.com/en-us/visualstudio/msbuild/msbuild-roslyncodetaskfactory?view=vs-2022).

Advantages:
In theory can run on all platforms
No manual triggering of T4 generation needed

Disadvantages:
Potentially slow during build, we should try to hash and see if code generation is really needed.

**Comment by agentsmith41** [comment]
closed by https://github.com/circles-arrows/blueprint41/pull/32
