### ISSUE TITLE
Logging doesn't work

### ISSUE THREAD

**Issue by hewhofreeks** [circles-arrows/blueprint41#3]
When you initialize your provider with:

```
            PersistenceProvider.CurrentPersistenceProvider =
                new Neo4JPersistenceProvider(XXX, XXX, XXX , withLogging: true);
```
The log file never gets created or written to. In Logger.cs this line:

` m_LogDirectory = Path.Combine(AppDomain.CurrentDomain.BaseDirectory ?? @"C:\", "TransactionLogs");`

needs to be

` LogDirectory = Path.Combine(AppDomain.CurrentDomain.BaseDirectory ?? @"C:\", "TransactionLogs");`

So the setter get called successfully and the LogFile property gets set.

**Comment by circles-arrows** [comment]
Thanks!

Next release this will be included
