### ISSUE TITLE
Relationship Events are never fired

### ISSUE THREAD

**Issue by hewhofreeks** [circles-arrows/blueprint41#7]
When trying to tap into events for Relationships I am unable to trigger them.

Relations["MY_RELATIONSHIP"].Events.OnRelationCreate  += Events_OnRelationCreated;

Will never trigger. When I look at the source code I cannot see anything calling the "RaiseOnRelationCreate" event or any of the other ones. Is this intentional? Is there a way to get around this in the current version of blueprint41?

**Comment by circles-arrows** [comment]
We looked at it and indeed it seems like the event is not raised where it should be. We'll fix the code and do a beta version release on nuget soon. That way you can at least try it out & use it before we finished updating the documentation, visual studio plugins, etc. for this release.

**Comment by circles-arrows** [comment]
Version 1.0.18-preview-1 is released on Nuget, this version should solve your event issues and adds support for Neo4j v4.x
Upgrading to this version is not a straight forward version upgrade of the nuget package, so please follow the instructions below if you want to try this out!

1. 	For projects "XXX.Generated" and "XXX.Model", update the Blueprint41 package to version "1.0.18-preview-1" via NuGet package manager.
2. 	For your client application/project:
	2.1	Via NuGet package manager, update the Blueprint41 package to version "1.0.18-preview-1".
	2.2	Via NuGet package manager, install the package Blueprint41.Neo4jDriver depending on the version of your Neo4j database. 
		See the Neo4j database version and its corresponding Blueprint41.Neo4jDriver version below.
		Neo4j 3.0 - 3.5 -> Blueprint41.Neo4jDriver.v3
		Neo4j 3.5 - 4.x -> Blueprint41.Neo4jDriver.v4

Please let us know if you run into problems!
