### ISSUE TITLE
Running with github action 

### ISSUE THREAD

**Issue by Eclegv** [circles-arrows/blueprint41#70]
# Kind of issue
- [ ] Regression 
- [x] Bug report
- [ ] Feature request
- [ ] Documentation issue or request

# In which operating systems have you tested?
- [ ] Windows
- [x] Linux (ubuntu-latest)
- [ ] MacOS

Hello !

I was setting up a github action for my dotnet project using blueprint41 and, while trying to run I encountered a problem with the Blueprint41.Build.Json.

>   Unhandled exception. System.IO.FileNotFoundException: Target folder '/home/runner/work/Astreis/Astreis/packages/back/Entities/Entities.Model/..\Entities.Generated' does not exist. Make sure to have a Blueprint41.Build.json with 'generatePath' set in the model project folder.
     at Blueprint41.Build.Generator.ValidatePaths(String modelPath, String generatePath)
     at Blueprint41.Build.Generator.Main(String[] args)
  Aborted (core dumped)

# How to fix it
To fit it, I had to modify the generatePath field from "..\\Entities.Generated" -> "..//Entities.Generated". Doing so doesn't cause any problems on windows, where I'm developing.

**Comment by circles-arrows** [comment]
We'll update "Blueprint41.Build" to translate the slashes and back-slashes to the correct path separators for the platform where it's running. That way it doesn't depend on anyone accidentally defining the target path using the right separator slashes.
