### ISSUE TITLE
Crash in Neo4jPersistenceProvider#FetchDatabaseInfo

### ISSUE THREAD

**Issue by robotgryphon** [circles-arrows/blueprint41#80]
I'm not sure what exactly the reproduction steps are; it looks like the Neo4j persistence manager blows up trying to read an empty collection (LINQ `First` instead of handling a null w/ `FirstOrDefault`)

![image](https://github.com/user-attachments/assets/9bcfae2a-7774-458b-87bf-4e720995d73a)

Relevant code: https://gist.github.com/robotgryphon/a8c9a873b8aba5eac917a4198424724d

Database set up:
- Running on Enterprise 5.23.0 (Neo4j Desktop, Linux)
- Created a `webadmin` user for management
  - Roles: architect, editor, publisher, reader, PUBLIC
- First run of this program code DID work to make an initial set of labels, but never again

**Comment by renkokarman** [comment]
Try to change your code from:
```C#
if(!dataModel.HasExecuted)
    dataModel.Execute(false); // <<<< DIES HERE
```
to:
```C#
dataModel.Execute(true);
```

The idea is that you can execute the rebuild of the data model (in memory) by applying the scripts that build up your model one at a time. If you supply "true" as the argument, Blueprint41 will generate and apply upgrade scripts to your datastore/graph, if the datastore did not have them applied before.

Therefore, you should always "Execute" the model with upgradeDatastore=true before you make any changes to your database. Preferably it's one of the first things you do at the application's main entry point.

So, when would you use the option to "Execute" the model with upgradeDatastore=false then? It's there for the scenario when your program needs to use the model but there is no datastore/graph available at runtime. For example, if you want to query the entities and relations from the model directly to generate documentation of your data model. You might want to do that automated from a build pipeline that has not permissions to connect to the datastore.
